# Generated by Django 5.0.1 on 2024-01-07 15:39

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_feedback_phone_number_alter_feedback_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
